name: Migration to Time-Tracker-V2 Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:
jobs:
  build:
    name: Migration to Time-Tracker-V2
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Init mypy
        run: echo Hello, world!

      - name: Run script to create database
        run: echo Running script o create data base!

      - name: Run test
        run: echo Running test!

      - name: Run test connection
        run: echo Running test connection!
        
      - name: Finish
        run: echo Finish!