name: Migration to Time-Tracker-V2 Pipeline
on:
  push:
    branches: [ "master" ]
jobs:
  build-and-check:
    name: Deploy setup
    runs-on: ubuntu-latest
    steps:
      -name: Checkout to master
      - uses: actions/checkout@master
      - name: Setup the environment
        run: echo Setting the environment!
      - name: Run all test
        run: echo Running all tests!